// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrganizerApi.Data;

namespace OrganizerApi.Migrations
{
    [DbContext(typeof(OrganizerDbContext))]
    [Migration("20200511151004_removedForeignKeyAttributes")]
    partial class removedForeignKeyAttributes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrganizerApi.Core.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Daydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Daydate");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("OrganizerApi.Models.Day", b =>
                {
                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("date");

                    b.ToTable("Days");
                });

            modelBuilder.Entity("OrganizerApi.Models.ScheduleEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Daydate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Daydate");

                    b.ToTable("ScheduleEntries");
                });

            modelBuilder.Entity("OrganizerApi.Models.ToDoEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Daydate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Daydate");

                    b.ToTable("ToDoEntries");
                });

            modelBuilder.Entity("OrganizerApi.Core.Models.Note", b =>
                {
                    b.HasOne("OrganizerApi.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("Daydate");
                });

            modelBuilder.Entity("OrganizerApi.Models.ScheduleEntry", b =>
                {
                    b.HasOne("OrganizerApi.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("Daydate");
                });

            modelBuilder.Entity("OrganizerApi.Models.ToDoEntry", b =>
                {
                    b.HasOne("OrganizerApi.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("Daydate");
                });
#pragma warning restore 612, 618
        }
    }
}
